Jenkinsfile

Very first attempt of a non-PR CI run failed because there was no PR to comment on: https://saml.buildvm.openshift.eng.bos.redhat.com:8888/job/art-tools/job/ocp-build-data-validator/job/master/1/display/redirect

Only attempt to comment on PR if there is a PR

---

tests/test_distgit.py
validator/distgit.py

Substitute variables in `distgit > branch` declarations.
```
distgit:
branch: foo-{VAR}
```

Accept vars in distgit > branch values

---

.idea/misc.xml
.idea/modules.xml
.idea/ocp-build-data-validator.iml
.idea/vcs.xml
validator/schema/image_schema.py
validator/schema/rpm_schema.py

Reverts openshift/ocp-build-data-validator#6

Revert "Allow maintainer"

---

setup.py
validator/schema/image_schema.py

pkg_managers: https://issues.redhat.com/browse/ART-1817
cli_alignment config is experimental for continuously aligning ART configuration with DPTP

Adding pkg_managers and alignment_prs config

---

deploy/Dockerfile.base
deploy/Dockerfile.update
deploy/README.md
deploy/build.base.yaml
deploy/build.update.yaml
deploy/secrets.yaml

Build and push updates to our validator whenever it's updated.

add production dockerfiles and deployment configs

---

validator/schema/releases_schema.py

Address problems validating correct usage like https://github.com/openshift/ocp-build-data/pull/1135#issuecomment-959813432

Permit overrides! in releases schema

---

deploy/Dockerfile.base

from my previous debug the filelock version in image is 3.0.12 does not meet the minimum version requirements to active virtualenv

use a higher version of filelock

---

tox.ini
validator/json_schemas/assembly_group_config.schema.json
validator/schema/image_schema.py
validator/support.py

add build_prodiles fields
add support for bug.yml 
update tox to using py3.8

update validator schema

---

validator/json_schemas/assembly_group_config.schema.json

the microshift section was added to advisories group and lead to failure like
https://github.com/openshift/ocp-build-data/pull/2417#issuecomment-1376731132

add microshift check

---

.devcontainer/devcontainer.json
requirements-dev.txt
tox.ini

fix error in https://app.snyk.io/org/openshift-art-build-bot/import-log/latest

fix snyk import error

---

deploy/Dockerfile.base

Introduce https://packaging.python.org/en/latest/key_projects/#build to build new-style pyproject.toml packages.

Dockerfile: Add Python package build

---

validator/json_schemas/assembly_group_config.schema.json

- Removes duplicate key
- Wildcard should be replaced with regex.

Fix broken assembly group schema

---

validator/json_schemas/image_config.base.schema.json

This is to support https://github.com/openshift-eng/doozer/pull/798.

Add exempted_packages field

---

tests/test_schema/test_image_schema.py
validator/__main__.py

Allow flag to skip vpn validations.
This is useful when we want to run validator in github CI

Allow to exclude vpn validations

---

validator/schema/streams_schema.py

to support https://github.com/openshift-eng/ocp-build-data/pull/3347

add support for upstream_image_mirror key

---

validator/json_schemas/image_config.base.schema.json

enable https://github.com/openshift-eng/ocp-build-data/pull/3560

allow image label com.redhat.prerelease

---

validator/json_schemas/image_config.base.schema.json

https://cswr.github.io/JsonSchema/spec/multiple_types/
slack ref https://redhat-internal.slack.com/archives/GDBRP5YJH/p1695829004021079
ready for lgtm, approve

Accept boolean or boolean value in quotes

---

validator/json_schemas/assembly_group_config.schema.json

ref. [OCP ART operator pre-release procedures](https://docs.google.com/document/d/1S_ivD8Sh85LuZKnClqvoRvIhn4hNJQA76jpfUaFZjUA/edit)

allow prerelease and advance advisories

---

validator/json_schemas/image_content.base.schema.json

Adding support for config options that we have had for a while
Needed for https://github.com/openshift-eng/ocp-build-data/pull/3723

Add mirror_manifest_list and set_build_variables image config options

---

validator/json_schemas/image_config.base.schema.json
validator/json_schemas/scanning.schema.json

For https://github.com/openshift-eng/ocp-build-data/pull/3893
```
scanning:
jira_integration:
enabled: true
```

SAST scan update

---

validator/json_schemas/image_config.base.schema.json
validator/json_schemas/scanning.schema.json

To match https://github.com/openshift-eng/ocp-build-data/pull/3907

[sast-scan] update schema

---

validator/schema/rpm_schema.py

Needed for https://github.com/openshift-eng/ocp-build-data/pull/3956

add 'web' to rpm config

---

validator/github.py

For https://github.com/openshift-eng/ocp-build-data/pull/3956

Add openshift/c2s-install to has_permitted_repo

---

validator/json_schemas/image_config.base.schema.json

For https://github.com/openshift-eng/art-tools/pull/237

Rename exempt packages config

---

validator/json_schemas/image_config.base.schema.json

Follows https://github.com/openshift-eng/art-tools/pull/260

ART-8476 Add alternative_upstream validation

---

validator/github.py

For https://github.com/openshift-eng/ocp-build-data/pull/4170

for rpms/ose-aws-ecr-image-credential-provider.yml
