tests/test_schema/test_modification_schema.py, validator/schema/image_schema.py, validator/schema/modification_schema.py, validator/schema/rpm_schema.py
New modification action `add` is introduced by ART-948 to allow to add external out-of-tree sources into dist-git.
For more information, see https://jira.coreos.com/browse/ART-948.
Signed-off-by: Yuxiang Zhu <yuxzhu@redhat.com>
=> ART-1112: Add new modification action `add`

Jenkinsfile
SO currrently the CI is broken even if no new code introduced like this [PR](https://github.com/openshift/ocp-build-data-validator/pull/10).
THe reason is because of change https://github.com/openshift/ocp-build-data-validator/commit/e180439a531f7cdae84bf439a2e038726a73091b#diff-58231b16fdee45a03a4ee3cf94a9f2c3
the type is String and in new image in art-ci-tool the type is Map.
=> fix ci fauilures

validator/__main__.py, validator/global_session.py, validator/support.py
Fixes https://github.com/openshift/ocp-build-data/pull/520 https://github.com/openshift/ocp-build-data/pull/519 https://github.com/openshift/ocp-build-data/pull/518 https://github.com/openshift/ocp-build-data/pull/517 https://github.com/openshift/ocp-build-data/pull/490 https://github.com/openshift/ocp-build-data/pull/447 https://github.com/openshift/ocp-build-data/pull/446
@thiagoalessio @vfreex @sosiouxme I don't exactly understand why our previous CI tests have not been caught by GitHub access rate limit but I am pretty sure if you curl 200+ images even with/without authentication will cause a problem (also I suspect base on IP or sth is there any change about or IP addresses from jenkins slaves? or maybe we used to have only one core so that multiple process acts like a single process …
=> adding global session to prevent too many requests rate limit

tests/test_schema/test_image_schema.py, tox.ini, validator/schema/image_schema.py, validator/schema/rpm_schema.py
enforce CI to check errors like this https://github.com/openshift/ocp-build-data/pull/526
=> make schema content.source.git.url stick to format git@host:org/repo.git

validator/__main__.py, validator/exceptions.py
```
[art@457fcce28224 validate-ocp-build-data]$ validate-ocp-build-data  ./ocp-build-data/images/openshift-enterprise-service-idler.yml 
Validating ./ocp-build-data/images/openshift-enterprise-service-idler.yml
Skipping validation of non_release images ./ocp-build-data/images/openshift-enterprise-service-idler.yml.
[art@457fcce28224 ocp-build-data]$ validate-ocp-build-data ./images/openshift-enterprise-service-idler.yml 
Validating ./images/openshift-enterprise-service-idler.yml
Skipping validation of non_release images ./images/openshift-enterprise-service-idler.yml.
```
=> Add NoReleaseSet support to sift out non_release in ocp-build-data

validator/global_session.py
This fixes the validation bug caused by retrying on 404s, in a case where a github branch does not exist. We want to get the 404 to detect a non-existent branch and then use the fallback branch.
=> Do not retry on 404s

validator/schema/image_schema.py
add to the schema options used by https://github.com/openshift/ocp-build-data/pull/863 and previous innovations in `ci_alignment`
=> [ART-2340] expand ci_alignment

setup.py
We need to create a new tag to let Jenkins publish new tool version to Pypi. This PR updates the setup.py file to define new version 0.2.2
=> Change version to 0.2.2

validator/__main__.py, validator/schema/__init__.py, validator/schema/releases_schema.py, validator/support.py
Right now we validate releases.yml - when validating any file. Since our releases.yml 
gets updated very frequently, with new keys added and not every key is added to 
schema or with some non-critical invalid entry, it results in validation fail.
That results in early exit of ocp-build-data-validator command where validation result 
for other files isn't run/displayed - [like this](https://coreos.slack.com/archives/GDBRP5YJH/p1646950803184889?thread_ts=1646927201.739019&cid=GDBRP5YJH)
So let's validate releases.yml only when it's requested (when a PR changes it).
I refactored releases validation as to how we validate other files with specific schema.
I updated the messaging a bit to avoid confusion as to what has been validated.
example see this - …
=> Do not validate releases.yml on every run

MANIFEST.in, SETUP_EDITOR.md, requirements.txt, validator/json_schemas/arches.schema.json, validator/json_schemas/arches_dict.schema.json, validator/json_schemas/assembly.schema.json, validator/json_schemas/assembly_basis.schema.json, validator/json_schemas/assembly_dependencies.schema.json, validator/json_schemas/assembly_group_config.schema.json, validator/json_schemas/assembly_issues.schema.json, validator/json_schemas/cachito.schema.json, validator/json_schemas/member_image.schema.json, validator/json_schemas/member_rpm.schema.json, validator/json_schemas/release.schema.json, validator/json_schemas/releases.schema.json, validator/json_schemas/repos.schema.json, validator/json_schemas/rhcos.schema.json, validator/json_schemas/streams.schema.json, validator/schema/releases_schema.py
Those JSON schema files can also be configured on editors or IDEs to support
auto-completion and instantaneous validation.
Note `releases.yml` may contain special fields (ending with `?` `!` `-`) for assembly inheritance.
In the future we may use Doozer to fill in the inherited fields and then run the output through the schema check, rather than try to validate inheritance fields directly.
Currently I added some most used special fields as separate fields to make IDEs/editors happy. Although they are not complete, it doesn't break the validator because the validator will remove all special suffixes before validate `releases.yml`.
=> Use JSON Schema to annotate and validate releases.yml

requirements.txt
build log shows it need a lower version
https://console-openshift-console.apps.art.xq1c.p1.openshiftapps.com/k8s/ns/art-tools/builds/ocp-build-data-validator-update-58/logs
=> use lower version to meet the build requirement

SETUP_EDITOR.md, tests/test_format.py, tests/test_schema/test_image_schema.py, validator/__main__.py, validator/json_schemas/arch.schema.json, validator/json_schemas/arches.schema.json, validator/json_schemas/arches_dict.schema.json, validator/json_schemas/assembly.schema.json, validator/json_schemas/assembly_basis.schema.json, validator/json_schemas/assembly_dependencies.schema.json, validator/json_schemas/assembly_group_config.schema.json, validator/json_schemas/assembly_issues.schema.json, validator/json_schemas/cachito.schema.json, validator/json_schemas/image_config.base.schema.json, validator/json_schemas/image_config.requires.schema.json, validator/json_schemas/image_config.schema.json, validator/json_schemas/image_content.base.schema.json, validator/json_schemas/image_content.requires.schema.json, validator/json_schemas/member_image.schema.json, validator/json_schemas/member_rpm.schema.json, validator/json_schemas/release.schema.json, validator/json_schemas/releases.schema.json, validator/json_schemas/repos.schema.json, validator/json_schemas/rhcos.schema.json, validator/json_schemas/source_modification.schema.json, validator/json_schemas/streams.schema.json, validator/schema/image_schema.py
Adds JSON shecma files and use them validate image configs and image
config overrides in releases.yml.
Note in normal image config .yml files, some fields are required (e.g.
`name`). But in releases.yml, we only need to provide overrides. That
means all image config fields used in releases.yml are optional.
To accomplish this, I split the schema definition for an object into
`.base.schema.json` and `.requires.schema.json` so that we can load `.base.schema.json` to validate releases.yml
while loading both `.base.schema.json` and `.requires.schema.json` to
validate normal image configs.
=> Use JSON schema to validate image configs

validator/json_schemas/rhcos.schema.json
basically whenever RHCOS adds another container, we can just allow it here like this.
eventually we'll probably need to make `machine-os-content` not required and add other restrictions, but that's for later.
=> [ART-3883] rhcos.schema.json: assembly may also specify rhel-coreos-8

requirements.txt, validator/distgit.py
pkgs.devel now redirects http to https (which is right) so we need tls connections to work. all it needs to work is to trust the system-trusted CA certs. this patches `requests` to do that.
=> finally fix CA trust issues

validator/global_session.py
It has been renamed to allowed_methods since urllib3 1.26.0.
Error example: https://github.com/openshift-eng/ocp-build-data/pull/3207
=> Fix TypeError "unexpected keyword argument method_whitelist"

validator/schema/image_schema.py, validator/schema/releases_schema.py
Do not print the whole error message which includes schema and image yml, since 
we are posting the output to PR comments - we only need a concise error about which
property is at fault
```
$ ocp-build-data-validator ../ocp-build-data/images/operator-lifecycle-manager.yml
Validating 1 file(s)...
Validating ../ocp-build-data/images/operator-lifecycle-manager.yml...
Schema mismatch: ../ocp-build-data/images/operator-lifecycle-manager.yml
Returned error: Additional properties are not allowed ('envs' was unexpected)
```
=> Print concise error message

validator/json_schemas/image_config.base.schema.json
As that is [what is
consumed](https://github.com/openshift-eng/art-tools/blob/9d03553e8e98affd84d23b3bb99af201a9722adc/doozer/doozerlib/distgit.py#L1849)
=> Use envs instead of env in image config

tests/test_schema/test_image_schema.py, validator/json_schemas/image_content.base.schema.json
There has been an incident where we unnoticedly configured an image to follow master. This has led to some pain. Requiring the branch to follow a regex prevents us to make the same mistake again.
=> Require regular expression for github branch

tests/test_schema/test_image_schema.py, validator/json_schemas/assembly_issues.schema.json, validator/json_schemas/image_content.base.schema.json
Reverts openshift-eng/ocp-build-data-validator#121
branch target can be a commit, see https://github.com/openshift-eng/ocp-build-data/blob/openshift-4.11/releases.yml#L372
=> Revert "Require regular expression for github branch"

validator/json_schemas/assembly_issues.schema.json
Reverts openshift-eng/ocp-build-data-validator#107
Before  merging let's plan on making releases.yml consistent with this change, otherwise PR validation is all but useless
=> Revert "Add `why` field to assembly issues"
